# Importing libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('data.csv')
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [3]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [5]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

## Taking care of the missing data

In [6]:
from sklearn.impute import SimpleImputer

In [7]:
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')

In [8]:
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [9]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

## Transform the independent variables

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [11]:
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], 
                       remainder = 'passthrough')

In [12]:
x = ct.fit_transform(x)
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

# Data sampling with Kfold Cross Validation

1. x_train
2. x_test
3. y_train
4. y_test

In [16]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold

In [17]:
kf = KFold(n_splits = 5, shuffle = True, random_state = 100)
sc = StandardScaler()

In [18]:
for train_index, test_index in kf.split(x):
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]
    x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
    x_test[:, 3:] = sc.transform(x_test[:, 3:])
    print(x_train)
    print("----------------------------")
    print(x_test)
    print("")

[[1.0 0.0 0.0 0.9275794157968308 0.8486580713459083]
 [0.0 0.0 1.0 -1.545965692994718 -1.5052442517451496]
 [0.0 1.0 0.0 -1.1094577326197388 -0.916768670972385]
 [0.0 0.0 1.0 0.054563495046872405 -0.2302138267374932]
 [0.0 1.0 0.0 0.34556880196352524 0.0422285717684166]
 [1.0 0.0 0.0 -0.38194446532810683 -0.5244516171238754]
 [0.0 1.0 0.0 1.8005953365467893 1.9275299694293098]
 [1.0 0.0 0.0 -0.090939158411454 0.3582617540352713]]
----------------------------
[[0.0 0.0 1.0 0.1677322255144597 -1.11292719789664]
 [1.0 0.0 0.0 1.5095900296301366 1.5352129155808003]]

[[1.0 0.0 0.0 0.5441082159257143 0.532171171713203]
 [0.0 1.0 0.0 -1.7798794181976751 -1.200727920096623]
 [0.0 0.0 1.0 -0.45188648441288115 -0.5268227177261351]
 [0.0 1.0 0.0 -0.11988825096668267 -0.25940001837276655]
 [0.0 0.0 1.0 -0.32277606029491496 -1.3932722636310482]
 [1.0 0.0 0.0 1.2081046828181115 1.206076374083691]
 [0.0 1.0 0.0 1.5401029162643098 1.5911650611525412]
 [1.0 0.0 0.0 -0.6178856011359805 0.05081031287714